loginPage/urls.py
from django.urls import path
from . import views

app_name = "loginPage"

urlpatterns = [
	path('', views.index, name = 'index'),
    path('login/', views.loginFunction, name = 'login'),
    path('logout/', views.logoutFunction, name = 'logout'),
    path('register/', views.registerFunction, name = 'register'),
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loginPage.urls'))
]

loginPage/models.py
from django.db import models

# Create your models here.

loginPage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1']

class LoginForm(forms.Form):
    username = forms.CharField(widget = forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'input name',
        'type' : 'text',
        'required' : True
    }))

    password = forms.CharField(widget = forms.PasswordInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'input password',
        'type' : 'password',
        'required' : True
    }))

loginPage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import *

# Create your views here.

def index(request):
    response = {'user': request.user}
    return render(request, 'index.html', response)

def loginFunction(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('loginPage:index')
            else:
                messages.error(request, 'invalid username or password')

    context = {'form' : form}
    return render(request, 'login.html', context)

def registerFunction(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('loginPage:login')
    
    context = {'form' : form}
    return render(request, 'register.html', context)

def logoutFunction(request):
    logout(request)
    return redirect('loginPage:login')

loginPage/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log-In</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    {% if user.is_authenticated %}
    <div class="container" id="content">
        <div class="card shadow rounded">
            <div class="card-body">
              <h2 class="card-title">Hello!</h2>
              <p class="card-text">Welcome back, {{user.username}}</p>
            </div>
        </div>
        <p id="logout"><a href="{% url 'loginPage:logout' %}" style="color: red;">Logout</a></p>
    </div>
    {% else %}
    <div class="container" id="content">
        <div class="card shadow rounded">
            <div class="card-body">
                <h2 class="card-title">Oh, hi!</h2>
                <p class="card-text">I think you should login first to access this page</p>
                <p>login <a href="{% url 'loginPage:login' %}">here</a>!</p>
            </div>
        </div>
        {% endif %}
    </div>

</body>
</html>

loginPage/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="container login-form">
        <div class="card shadow rounded">
            <div class="card-header">
                <h3>Login</h3>
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group" style="padding-top: 3%;">
                  <label for="username">Username :</label>
                  {{form.username}}
                </div>
                <div class="form-group">
                  <label for="password">Password :</label>
                  {{form.password}}
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
    
            <div class="error-msg">
                {% for msg in messages %}
                    {{msg}}
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="container register-link">
        <p>Doesn't have any account? Register <a href="{% url 'loginPage:register' %}">here</a></p>
    </div>
</body>
</html>

loginPage/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign up</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
</head>
<body>

    <div class="container register-form">
        <div class="card shadow rounded">
            <div class="card-header">
                <h3>Register</h3>
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div>
                        <label for="username">Username :</label>
                    </div>
                    <div>
                        {{form.username}}
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <label for="password1">Password :</label>
                    </div>
                    <div>
                        {{form.password1}}
                    </div>
                </div>
                <div class="form-group">
                    <div>
                        <label for="password2">Password confirmation :</label>
                    </div>
                    <div>
                        {{form.password2}}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {{form.username.errors}}
            {{form.password1.errors}}
            {{form.password2.errors}}
        </div>
    </div>

    <div class="container login-link">
        <p>Already have an account? Sign in <a href="{% url 'loginPage:login' %}">here</a></p>
    </div>

</body>
</html>